### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ixshariff** [NickThissen/iRacingSdkWrapper#14]
Hi Nick,
Great library! Can I ask if this software free (as in beer)? GNU Free license terms? No copyright or terms that I can see.
Thanks,
Irfan

**Comment by ixshariff** [comment]
Found it, it's in TimeDelta.cs. It's GNU General Public License.

**Comment by NickThissen** [comment]
Full disclosure - the TimeDelta is coming straight from an old open source software (iRTVO) with no changes. I added the license now, feel free to use for any purpose.
