### ISSUE TITLE
Sometimes CarIdx data is not available for all idx

### ISSUE THREAD

**Issue by sushi86** [NickThissen/iRacingSdkWrapper#6]
Hey,
my problem is in the CarIdx* arrays sometimes not all cars are available. 
For example a short time after the car with idx 1 drove over the finish line there is no data for this idx.

Is this because iRacing is not giving us data for all cars?

I noticed because I want to create a list with relative times to me from all cars on track, but sometimes cars disappear from the list.

Thanks for any help =)

**Comment by sushi86** [comment]
Sorry for this ping, but I dont find any solution for this @NickThissen

**Comment by JasperGroeneweg** [comment]
Hi, Iracing will only send telemetry for the amount of cars you have set in graphics options, maybe that is what you are seeing?

**Comment by sushi86** [comment]
Thanks for the answer :)
